In [1]:
import pandas as pd 
import numpy as np 
import tensorflow as tf 
from sklearn import model_selection

In [2]:
data=pd.read_excel("ENB2012_data.xlsx",0)
data.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [3]:
data.shape

(768, 10)

In [4]:
data=data.drop(columns="Y2")
data.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84

In [5]:
y=data[["Y1"]]
y

        Y1
0    15.55
1    15.55
2    15.55
3    15.55
4    20.84
..     ...
763  17.88
764  16.54
765  16.44
766  16.48
767  16.64

[768 rows x 1 columns]

In [6]:
x=data.drop(columns="Y1")
x

       X1     X2     X3      X4   X5  X6   X7  X8
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0
..    ...    ...    ...     ...  ...  ..  ...  ..
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5

[768 rows x 8 columns]

In [7]:
X=x.to_numpy()
X

array([[9.800e-01, 5.145e+02, 2.940e+02, ..., 2.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 3.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 4.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 3.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 4.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 5.000e+00, 4.000e-01,
        5.000e+00]])

In [8]:
Y=y.to_numpy()
Y

array([[15.55 ],
       [15.55 ],
       [15.55 ],
       [15.55 ],
       [20.84 ],
       [21.46 ],
       [20.71 ],
       [19.68 ],
       [19.5  ],
       [19.95 ],
       [19.34 ],
       [18.31 ],
       [17.05 ],
       [17.41 ],
       [16.95 ],
       [15.98 ],
       [28.52 ],
       [29.9  ],
       [29.63 ],
       [28.75 ],
       [24.77 ],
       [23.93 ],
       [24.77 ],
       [23.93 ],
       [ 6.07 ],
       [ 6.05 ],
       [ 6.01 ],
       [ 6.04 ],
       [ 6.37 ],
       [ 6.4  ],
       [ 6.366],
       [ 6.4  ],
       [ 6.85 ],
       [ 6.79 ],
       [ 6.77 ],
       [ 6.81 ],
       [ 7.18 ],
       [ 7.1  ],
       [ 7.1  ],
       [ 7.1  ],
       [10.85 ],
       [10.54 ],
       [10.77 ],
       [10.56 ],
       [ 8.6  ],
       [ 8.49 ],
       [ 8.45 ],
       [ 8.5  ],
       [24.58 ],
       [24.63 ],
       [24.63 ],
       [24.59 ],
       [29.03 ],
       [29.87 ],
       [29.14 ],
       [28.09 ],
       [26.28 ],
       [26.91 ],
       [26.37 ],
       [25.27 ],
       [23.53 ],
       [24.03 ],
       [23.54 ],
       [22.58 ],
       [35.56 ],
       [37.12 ],
       [36.9  ],
       [35.94 ],
       [32.96 ],
       [32.12 ],
       [32.94 ],
       [32.21 ],
       [10.36 ],
       [10.43 ],
       [10.36 ],
       [10.39 ],
       [10.71 ],
       [10.8  ],
       [10.7  ],
       [10.75 ],
       [11.11 ],
       [11.13 ],
       [11.09 ],
       [11.16 ],
       [11.68 ],
       [11.69 ],
       [11.7  ],
       [11.69 ],
       [15.41 ],
       [15.2  ],
       [15.42 ],
       [15.21 ],
       [12.96 ],
       [12.97 ],
       [12.93 ],
       [13.02 ],
       [24.29 ],
       [24.31 ],
       [24.13 ],
       [24.25 ],
       [28.88 ],
       [29.68 ],
       [28.83 ],
       [27.9  ],
       [26.48 ],
       [27.02 ],
       [26.33 ],
       [25.36 ],
       [23.75 ],
       [24.23 ],
       [23.67 ],
       [22.79 ],
       [35.65 ],
       [37.26 ],
       [36.97 ],
       [36.03 ],
       [33.16 ],
       [32.4  ],
       [33.12 ],
       [32.41 ],
       [10.42 ],
       [10.46 ],
       [10.32 ],
       [10.45 ],
       [10.64 ],
       [10.72 ],
       [10.55 ],
       [10.68 ],
       [11.45 ],
       [11.46 ],
       [11.32 ],
       [11.49 ],
       [11.45 ],
       [11.42 ],
       [11.33 ],
       [11.43 ],
       [15.41 ],
       [15.18 ],
       [15.34 ],
       [15.19 ],
       [12.88 ],
       [13.   ],
       [12.97 ],
       [13.04 ],
       [24.28 ],
       [24.4  ],
       [24.11 ],
       [24.35 ],
       [28.07 ],
       [29.01 ],
       [29.62 ],
       [29.05 ],
       [25.41 ],
       [26.47 ],
       [26.89 ],
       [26.46 ],
       [22.93 ],
       [23.84 ],
       [24.17 ],
       [23.87 ],
       [35.78 ],
       [35.48 ],
       [36.97 ],
       [36.7  ],
       [32.52 ],
       [33.28 ],
       [32.33 ],
       [33.24 ],
       [10.39 ],
       [10.34 ],
       [10.35 ],
       [10.38 ],
       [10.77 ],
       [10.68 ],
       [10.68 ],
       [10.7  ],
       [11.22 ],
       [11.16 ],
       [11.1  ],
       [11.14 ],
       [11.59 ],
       [11.6  ],
       [11.53 ],
       [11.61 ],
       [15.16 ],
       [15.36 ],
       [15.12 ],
       [15.36 ],
       [12.68 ],
       [12.63 ],
       [12.71 ],
       [12.73 ],
       [24.38 ],
       [24.23 ],
       [24.04 ],
       [24.32 ],
       [29.06 ],
       [28.05 ],
       [28.86 ],
       [29.79 ],
       [26.44 ],
       [25.37 ],
       [26.33 ],
       [27.03 ],
       [23.8  ],
       [22.8  ],
       [23.59 ],
       [24.24 ],
       [36.86 ],
       [35.89 ],
       [35.45 ],
       [37.1  ],
       [33.08 ],
       [32.38 ],
       [33.09 ],
       [32.31 ],
       [10.08 ],
       [10.15 ],
       [10.07 ],
       [10.14 ],
       [10.66 ],
       [10.68 ],
       [10.53 ],
       [10.72 ],
       [11.18 ],
       [11.22 ],
       [11.07 ],
       [11.2  ],
       [11.44 ],
       [11.42 ],
       [11.33 ],
       [11.43 ],
       [15.4  ],
       [15.19 ],
       [15.32 ],
       [15.16 ],
       [12.85 ],
       [13.04 ],
       [13.   ],
       [13.   ],
       [24.35 ],
       [24.33 ],
       [24.03 ],
       [24.26 ],
       [29.83 ],
       [29.08 ],
       [28.03 ],
       [29.02 ],
       [27.03 ],
       [26.45 ],
       [25.36 ],
       [26.45 ],
       [24.37 ],
       [23.89 ],
       [22.89 ],
       [23.86 ],
       [37.03 ],
       [36.71 ],
       [36.77 ],
       [35.48 ],
       [32.31 ],
       [33.21 ],
       [32.46 ],
       [33.27 ],
       [10.47 ],
       [10.37 ],
       [10.34 ],
       [10.39 ],
       [10.78 ],
       [10.7  ],
       [10.67 ],
       [13.69 ],
       [11.21 ],
       [11.14 ],
       [11.11 ],
       [11.16 ],
       [11.38 ],
       [11.34 ],
       [11.22 ],
       [11.34 ],
       [15.16 ],
       [15.37 ],
       [15.12 ],
       [15.36 ],
       [12.59 ],
       [12.74 ],
       [12.8  ],
       [12.62 ],
       [28.15 ],
       [28.15 ],
       [28.37 ],
       [28.41 ],
       [32.68 ],
       [33.48 ],
       [32.84 ],
       [32.   ],
       [29.54 ],
       [30.05 ],
       [29.6  ],
       [28.66 ],
       [26.84 ],
       [27.27 ],
       [26.97 ],
       [26.19 ],
       [38.67 ],
       [40.03 ],
       [39.86 ],
       [39.04 ],
       [36.96 ],
       [36.13 ],
       [36.91 ],
       [36.43 ],
       [12.43 ],
       [12.5  ],
       [12.41 ],
       [12.45 ],
       [12.57 ],
       [12.65 ],
       [12.57 ],
       [12.63 ],
       [12.78 ],
       [12.93 ],
       [12.73 ],
       [12.72 ],
       [13.17 ],
       [13.18 ],
       [13.17 ],
       [13.18 ],
       [17.5  ],
       [17.35 ],
       [17.52 ],
       [17.37 ],
       [15.09 ],
       [15.12 ],
       [15.08 ],
       [15.16 ],
       [28.67 ],
       [28.57 ],
       [28.18 ],
       [28.6  ],
       [32.46 ],
       [33.27 ],
       [32.33 ],
       [31.66 ],
       [29.34 ],
       [29.87 ],
       [29.27 ],
       [28.4  ],
       [25.74 ],
       [25.98 ],
       [25.38 ],
       [24.94 ],
       [38.57 ],
       [40.19 ],
       [39.97 ],
       [38.98 ],
       [36.95 ],
       [36.28 ],
       [36.86 ],
       [36.45 ],
       [12.35 ],
       [12.45 ],
       [12.16 ],
       [12.3  ],
       [12.33 ],
       [12.29 ],
       [12.2  ],
       [12.49 ],
       [12.85 ],
       [12.87 ],
       [12.73 ],
       [12.95 ],
       [13.05 ],
       [12.93 ],
       [12.77 ],
       [13.   ],
       [17.14 ],
       [16.84 ],
       [17.02 ],
       [17.11 ],
       [14.34 ],
       [14.66 ],
       [14.6  ],
       [14.6  ],
       [28.67 ],
       [28.56 ],
       [28.17 ],
       [28.63 ],
       [31.63 ],
       [32.4  ],
       [32.68 ],
       [32.29 ],
       [28.4  ],
       [29.4  ],
       [29.43 ],
       [29.07 ],
       [24.7  ],
       [25.48 ],
       [25.37 ],
       [25.17 ],
       [39.04 ],
       [38.35 ],
       [39.81 ],
       [39.83 ],
       [35.99 ],
       [36.59 ],
       [35.64 ],
       [36.52 ],
       [11.8  ],
       [12.03 ],
       [11.98 ],
       [11.69 ],
       [12.41 ],
       [12.28 ],
       [12.1  ],
       [12.19 ],
       [12.34 ],
       [12.46 ],
       [12.31 ],
       [12.12 ],
       [12.97 ],
       [13.01 ],
       [12.74 ],
       [12.84 ],
       [16.83 ],
       [16.93 ],
       [16.66 ],
       [16.86 ],
       [13.91 ],
       [14.34 ],
       [13.95 ],
       [13.99 ],
       [28.7  ],
       [28.55 ],
       [28.15 ],
       [28.62 ],
       [32.67 ],
       [31.69 ],
       [32.07 ],
       [33.28 ],
       [29.47 ],
       [28.42 ],
       [29.08 ],
       [29.88 ],
       [25.66 ],
       [24.96 ],
       [25.43 ],
       [26.   ],
       [40.   ],
       [38.84 ],
       [38.33 ],
       [40.12 ],
       [36.95 ],
       [36.45 ],
       [36.81 ],
       [36.26 ],
       [12.32 ],
       [12.3  ],
       [12.18 ],
       [12.43 ],
       [12.36 ],
       [12.49 ],
       [12.17 ],
       [12.28 ],
       [12.91 ],
       [12.95 ],
       [12.67 ],
       [12.86 ],
       [12.95 ],
       [13.   ],
       [12.86 ],
       [12.92 ],
       [16.99 ],
       [16.69 ],
       [16.56 ],
       [16.62 ],
       [14.33 ],
       [14.61 ],
       [14.61 ],
       [14.65 ],
       [28.69 ],
       [28.58 ],
       [28.15 ],
       [28.61 ],
       [33.13 ],
       [32.31 ],
       [31.53 ],
       [32.46 ],
       [29.71 ],
       [29.09 ],
       [28.31 ],
       [29.39 ],
       [25.7  ],
       [25.17 ],
       [24.6  ],
       [25.49 ],
       [39.89 ],
       [39.83 ],
       [39.01 ],
       [38.65 ],
       [35.69 ],
       [36.64 ],
       [36.06 ],
       [36.7  ],
       [12.12 ],
       [11.67 ],
       [11.64 ],
       [12.02 ],
       [12.27 ],
       [12.19 ],
       [12.25 ],
       [12.27 ],
       [12.47 ],
       [12.12 ],
       [12.18 ],
       [12.47 ],
       [12.93 ],
       [12.82 ],
       [12.78 ],
       [13.02 ],
       [16.73 ],
       [16.86 ],
       [16.76 ],
       [16.92 ],
       [13.68 ],
       [13.99 ],
       [14.16 ],
       [13.86 ],
       [32.26 ],
       [32.26 ],
       [32.49 ],
       [32.53 ],
       [36.47 ],
       [37.24 ],
       [36.66 ],
       [35.96 ],
       [31.89 ],
       [32.39 ],
       [32.09 ],
       [31.29 ],
       [29.22 ],
       [29.91 ],
       [29.53 ],
       [28.65 ],
       [41.4  ],
       [42.62 ],
       [42.5  ],
       [41.67 ],
       [40.78 ],
       [39.97 ],
       [40.71 ],
       [40.43 ],
       [14.52 ],
       [14.61 ],
       [14.5  ],
       [14.55 ],
       [14.51 ],
       [14.6  ],
       [14.5  ],
       [14.58 ],
       [14.51 ],
       [14.7  ],
       [14.42 ],
       [14.42 ],
       [15.23 ],
       [15.23 ],
       [15.23 ],
       [15.23 ],
       [19.52 ],
       [19.36 ],
       [19.48 ],
       [19.42 ],
       [15.09 ],
       [17.17 ],
       [17.14 ],
       [17.14 ],
       [32.82 ],
       [32.71 ],
       [32.24 ],
       [32.72 ],
       [35.84 ],
       [36.57 ],
       [36.06 ],
       [35.69 ],
       [32.48 ],
       [32.74 ],
       [32.13 ],
       [31.64 ],
       [28.95 ],
       [29.49 ],
       [28.64 ],
       [28.01 ],
       [41.64 ],
       [43.1  ],
       [42.74 ],
       [41.92 ],
       [40.78 ],
       [40.15 ],
       [40.57 ],
       [40.42 ],
       [14.54 ],
       [14.45 ],
       [14.18 ],
       [14.5  ],
       [14.7  ],
       [14.66 ],
       [14.4  ],
       [14.71 ],
       [14.75 ],
       [14.71 ],
       [14.33 ],
       [14.62 ],
       [15.34 ],
       [15.29 ],
       [15.09 ],
       [15.3  ],
       [19.2  ],
       [18.88 ],
       [18.9  ],
       [19.12 ],
       [16.76 ],
       [17.23 ],
       [17.26 ],
       [17.15 ],
       [32.82 ],
       [32.69 ],
       [32.23 ],
       [32.75 ],
       [34.24 ],
       [34.95 ],
       [35.05 ],
       [34.29 ],
       [31.28 ],
       [32.12 ],
       [32.05 ],
       [31.84 ],
       [28.67 ],
       [29.67 ],
       [29.47 ],
       [28.91 ],
       [41.26 ],
       [41.3  ],
       [42.49 ],
       [42.08 ],
       [39.32 ],
       [39.84 ],
       [38.89 ],
       [39.68 ],
       [13.97 ],
       [14.22 ],
       [14.1  ],
       [13.78 ],
       [14.07 ],
       [14.03 ],
       [13.94 ],
       [13.86 ],
       [14.32 ],
       [14.56 ],
       [14.33 ],
       [14.08 ],
       [15.16 ],
       [15.18 ],
       [14.72 ],
       [14.9  ],
       [18.48 ],
       [18.71 ],
       [18.48 ],
       [18.46 ],
       [16.47 ],
       [16.35 ],
       [16.55 ],
       [16.74 ],
       [32.85 ],
       [32.67 ],
       [32.21 ],
       [32.74 ],
       [36.45 ],
       [35.73 ],
       [35.4  ],
       [36.57 ],
       [32.38 ],
       [31.66 ],
       [32.15 ],
       [32.75 ],
       [28.93 ],
       [28.05 ],
       [28.64 ],
       [29.52 ],
       [42.77 ],
       [41.73 ],
       [41.32 ],
       [42.96 ],
       [40.68 ],
       [40.4  ],
       [40.6  ],
       [40.11 ],
       [14.37 ],
       [14.48 ],
       [14.32 ],
       [14.44 ],
       [14.6  ],
       [14.7  ],
       [14.47 ],
       [14.66 ],
       [14.54 ],
       [14.62 ],
       [14.53 ],
       [14.71 ],
       [15.34 ],
       [15.29 ],
       [15.09 ],
       [15.3  ],
       [19.06 ],
       [19.13 ],
       [19.   ],
       [18.84 ],
       [16.44 ],
       [16.9  ],
       [16.94 ],
       [16.77 ],
       [32.84 ],
       [32.72 ],
       [32.21 ],
       [32.73 ],
       [35.67 ],
       [35.01 ],
       [34.72 ],
       [35.24 ],
       [32.31 ],
       [31.81 ],
       [31.12 ],
       [32.06 ],
       [30.   ],
       [29.5  ],
       [29.06 ],
       [29.92 ],
       [42.11 ],
       [41.96 ],
       [41.09 ],
       [40.79 ],
       [38.82 ],
       [39.72 ],
       [39.31 ],
       [39.86 ],
       [14.41 ],
       [14.19 ],
       [14.17 ],
       [14.39 ],
       [12.43 ],
       [12.63 ],
       [12.76 ],
       [12.42 ],
       [14.12 ],
       [14.28 ],
       [14.37 ],
       [14.21 ],
       [14.96 ],
       [14.92 ],
       [14.92 ],
       [15.16 ],
       [17.69 ],
       [18.19 ],
       [18.16 ],
       [17.88 ],
       [16.54 ],
       [16.44 ],
       [16.48 ],
       [16.64 ]])

# model building

In [9]:
trainx,trainy,testx,testy=model_selection.train_test_split(X,Y,train_size=.70,random_state=3)

In [178]:
epoch=10
batch_size=70

In [179]:
model1=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512,activation=tf.nn.relu),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(256,activation=tf.nn.relu),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(128,activation=tf.nn.log_softmax),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(1,activation='linear')])

In [188]:
optimiser=tf.keras.optimizers.Adam()
model1.compile(optimizer=optimiser,loss=tf.keras.losses.huber,metrics=tf.keras.metrics.mean_absolute_error)

In [189]:
model1.fit(trainx,testx,batch_size=70,epochs=5)

Epoch 1/5
8/8 [==============================] - 0s 8ms/step - loss: 5.7219 - mean_absolute_error: 6.2041
Epoch 2/5
8/8 [==============================] - 0s 8ms/step - loss: 5.2562 - mean_absolute_error: 5.7308
Epoch 3/5
8/8 [==============================] - 0s 8ms/step - loss: 5.3189 - mean_absolute_error: 5.8001
Epoch 4/5
8/8 [==============================] - 0s 6ms/step - loss: 5.3011 - mean_absolute_error: 5.7765
Epoch 5/5
8/8 [==============================] - 0s 6ms/step - loss: 5.3322 - mean_absolute_error: 5.8109

In [190]:
model1.evaluate(trainy, testy)

8/8 [==============================] - 0s 3ms/step - loss: 3.2826 - mean_absolute_error: 3.7632

[3.282616138458252, 3.7632453441619873]

In [191]:
model1.predict(trainy)

array([[26.543594 ],
       [13.994642 ],
       [13.710858 ],
       [26.761175 ],
       [13.710858 ],
       [26.762753 ],
       [26.719023 ],
       [13.989318 ],
       [20.59115  ],
       [14.148512 ],
       [27.43562  ],
       [13.710858 ],
       [27.65228  ],
       [24.353136 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [27.330656 ],
       [36.34451  ],
       [13.710858 ],
       [13.710858 ],
       [13.974192 ],
       [26.576597 ],
       [27.346394 ],
       [26.947865 ],
       [13.710858 ],
       [13.710858 ],
       [36.515545 ],
       [21.408134 ],
       [24.270552 ],
       [28.015745 ],
       [13.710858 ],
       [27.057116 ],
       [21.098314 ],
       [26.879938 ],
       [14.0334015],
       [26.913036 ],
       [24.171164 ],
       [23.987757 ],
       [14.168675 ],
       [13.885287 ],
       [26.828924 ],
       [26.459652 ],
       [13.710858 ],
       [35.97594  ],
       [27.624243 ],
       [15.43644  ],
       [27.861942 ],
       [27.337568 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [27.374529 ],
       [21.364351 ],
       [13.710858 ],
       [36.282513 ],
       [21.584002 ],
       [13.710858 ],
       [15.194066 ],
       [27.522108 ],
       [23.988039 ],
       [13.710858 ],
       [13.710858 ],
       [24.17224  ],
       [24.310385 ],
       [15.220556 ],
       [24.527565 ],
       [35.95515  ],
       [36.292965 ],
       [27.465792 ],
       [13.968932 ],
       [27.828587 ],
       [13.710858 ],
       [13.933781 ],
       [13.710858 ],
       [36.15772  ],
       [36.00169  ],
       [14.057151 ],
       [26.47087  ],
       [27.029509 ],
       [15.784537 ],
       [15.600129 ],
       [20.79326  ],
       [15.4918165],
       [15.605963 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [24.443264 ],
       [14.031061 ],
       [26.970839 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [15.6524725],
       [13.710858 ],
       [27.895302 ],
       [27.166641 ],
       [15.61181  ],
       [27.407469 ],
       [21.189383 ],
       [13.93893  ],
       [24.57346  ],
       [13.710858 ],
       [35.96551  ],
       [26.892609 ],
       [21.278824 ],
       [27.579254 ],
       [27.493933 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [13.956716 ],
       [14.089731 ],
       [13.710858 ],
       [13.710858 ],
       [35.99133  ],
       [13.710858 ],
       [24.129576 ],
       [13.710858 ],
       [13.710858 ],
       [26.844484 ],
       [13.710858 ],
       [36.308254 ],
       [27.108854 ],
       [26.525648 ],
       [35.830517 ],
       [15.583533 ],
       [13.710858 ],
       [13.710858 ],
       [14.015329 ],
       [13.710858 ],
       [27.13952  ],
       [13.710858 ],
       [36.53697  ],
       [26.639042 ],
       [36.35496  ],
       [13.710858 ],
       [13.98174  ],
       [13.710858 ],
       [27.772425 ],
       [26.851885 ],
       [13.710858 ],
       [26.670055 ],
       [23.689915 ],
       [13.961442 ],
       [23.900274 ],
       [13.710858 ],
       [14.062674 ],
       [13.710858 ],
       [26.677141 ],
       [13.710858 ],
       [15.634337 ],
       [21.012617 ],
       [26.707785 ],
       [13.710858 ],
       [20.925669 ],
       [35.820126 ],
       [26.644094 ],
       [13.710858 ],
       [36.318737 ],
       [24.042334 ],
       [13.710858 ],
       [14.115408 ],
       [26.553623 ],
       [26.805784 ],
       [15.565585 ],
       [27.49497  ],
       [13.710858 ],
       [26.733149 ],
       [27.151264 ],
       [20.918219 ],
       [27.009047 ],
       [26.99891  ],
       [13.710858 ],
       [35.918972 ],
       [26.728117 ],
       [35.74782  ],
       [15.315541 ],
       [24.12851  ],
       [26.790768 ],
       [27.243544 ],
       [26.991676 ],
       [15.447825 ],
       [26.82385  ],
       [15.755534 ],
       [27.713657 ],
       [13.710858 ],
       [13.710858 ],
       [20.831419 ],
       [13.710858 ],
       [20.969122 ],
       [13.710858 ],
       [15.353822 ],
       [36.16272  ],
       [13.710858 ],
       [27.23229  ],
       [13.710858 ],
       [27.31939  ],
       [13.710858 ],
       [14.153257 ],
       [35.986446 ],
       [27.35136  ],
       [13.710858 ],
       [27.982351 ],
       [13.710858 ],
       [13.710858 ],
       [14.049286 ],
       [15.555378 ],
       [13.710858 ],
       [26.92008  ],
       [21.49106  ],
       [27.313467 ],
       [27.954245 ],
       [15.503806 ],
       [13.710858 ],
       [27.675093 ],
       [13.710858 ],
       [21.54515  ],
       [24.227644 ],
       [27.067347 ],
       [20.78808  ],
       [14.012504 ],
       [13.710858 ],
       [20.747358 ],
       [15.459726 ],
       [13.710858 ],
       [36.147243 ]], dtype=float32)